[workspace]
resolver = "3"
members = ["psx-bench", "psx-core", "psx-dbg", "psx-emu"]

[profile.release]
lto = "fat"
debug = true
codegen-units = 1

[profile.dev]
opt-level = 3
debug-assertions = true
